name: sckinetics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.20
  - r-base=4.4.1
  - rpy2=3.6.6
  - pip
  - conda-pack=0.9.1
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - joblib=1.5.3
  - tqdm=4.67.3
  - numba=0.65.0
  - anndata=0.11.4
  - matplotlib-base=3.10.8
  - seaborn=0.13.2
  - statsmodels=0.14.6
  - umap-learn=0.5.12
  - networkx=3.4.2
  - h5py=3.16.0
  - biopython=1.87
  - mygene=3.2.2
  - validators=0.35.0
  - validate_email=1.3
  - jaro-winkler=2.0.3
  - scanpy=1.11.5
  - scvelo=0.3.4
  - gimmemotifs=0.18.2
  - moods=1.9.4.2
  - bedtools=2.31.1
  - homer=5.1
  - pybedtools=0.12.0
  - pysam=0.22.1
  - bioconductor-chipseeker=1.42.0
  - bioconductor-genomicfeatures=1.58.0
  - bioconductor-genomicranges=1.58.0
  - bioconductor-iranges=2.40.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-txdb.mmusculus.ucsc.mm39.knowngene=3.20.0
  - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene=3.10.0
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene=3.20.0
  - pip:
      - IPy==1.1
      - compress_json==1.1.1
      - environments_utils==1.0.15
      - ucsc_genomes_downloader==1.1.26
      - userinput==1.0.22
      - validate_version_code==1.0.5
